#!/bin/sh
set -e

# only configure everything once
if [ ! -f /etc/postfix/groupoffice ]; then
  exit 0
fi

echo "If you remove this file the groupoffice-mailserver will reconfigure postfix on the next upgrade" > /etc/postfix/groupoffice;

if ! id -u vmail >/dev/null 2>&1; then
	echo "Adding new user 'vmail' (UID=150) with group 'mail'";	
	useradd -r -u 150 -g mail -d /var/mail/vhosts -m -s /sbin/nologin -c "Virtual Mailbox" vmail
fi

chown vmail:mail /var/mail/vhosts
chown -R vmail:mail /var/lib/dovecot/db

#disable default system auth because it slows down the login
sed -i 's/!include auth-system.conf.ext/#!include auth-system.conf.ext/' /etc/dovecot/conf.d/10-auth.conf


# Postfix config
cp /etc/hostname /etc/mailname

# SASL settings
# This will make Postfix authenticate users via Dovecot. Users mail clients will connect directly to Postfix
# for sending mail and we need them to authenticate.

# About submission_header_checks:
# https://askubuntu.com/questions/78163/when-sending-email-with-postfix-how-can-i-hide-the-sender-s-ip-and-username-in

postconf -e 'smtpd_sasl_auth_enable = no' && \
postconf -e 'smtpd_sasl_type = dovecot' && \
postconf -e 'smtpd_sasl_path = private/auth' && \
postconf -e 'smtpd_sasl_authenticated_header = no' && \
postconf -e 'smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_non_fqdn_sender, reject_non_fqdn_recipient, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_hostname, reject_unknown_sender_domain permit' && \
postconf -e 'smtpd_data_restrictions = reject_unauth_pipelining, reject_multi_recipient_bounce, permit' && \
postconf -e 'smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination' && \
postconf -e 'smtpd_sasl_path = private/auth' && \
postconf -e 'smtp_tls_security_level = may' && \
postconf -e 'broken_sasl_auth_clients = yes' && \
postconf -e 'virtual_minimum_uid = 150' && \
postconf -e 'virtual_uid_maps = static:150' && \
postconf -e 'virtual_gid_maps = static:8' && \
postconf -e 'virtual_mailbox_base = /var/mail/vhosts' && \
postconf -e 'virtual_alias_domains =' && \
postconf -e 'virtual_alias_maps = proxy:mysql:$config_directory/mysql_virtual_alias_maps.cf' && \
postconf -e 'virtual_mailbox_domains = proxy:mysql:$config_directory/mysql_virtual_mailbox_domains.cf' && \
postconf -e 'virtual_mailbox_maps = proxy:mysql:$config_directory/mysql_virtual_mailbox_maps.cf' && \
postconf -e 'virtual_transport = lmtp:unix:private/dovecot-lmtp' && \
postconf -e 'default_destination_concurrency_limit = 5' && \
postconf -e 'relay_destination_concurrency_limit = 1' && \
postconf -e 'message_size_limit = 20480000' && \
postconf -M submission/inet="submission   inet   n   -   n   -   -   smtpd" && \
postconf -P "submission/inet/syslog_name=postfix/submission" && \
postconf -P "submission/inet/smtpd_tls_security_level=encrypt" && \
postconf -P "submission/inet/smtpd_etrn_restrictions=reject" && \
postconf -P "submission/inet/smtpd_sasl_type=dovecot" && \
postconf -P "submission/inet/smtpd_sasl_path=private/auth" && \
postconf -P "submission/inet/smtpd_sasl_security_options=noanonymous" && \
postconf -P "submission/inet/smtpd_sasl_local_domain=$myhostname" && \
postconf -P "submission/inet/smtpd_sasl_auth_enable=yes" && \
postconf -P "submission/inet/milter_macro_daemon_name=ORIGINATING" && \
postconf -P "submission/inet/smtpd_client_restrictions=permit_sasl_authenticated,reject" && \
postconf -P "submission/inet/smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject" && \
postconf -M subcleanup/unix="subcleanup   unix n    -       -       -       0       cleanup" && \
postconf -P "subcleanup/unix/header_checks=regexp:/etc/postfix/submission_header_checks" && \
postconf -P "submission/inet/smtpd_client_message_rate_limit=2" && \
postconf -P "submission/inet/anvil_rate_time_unit=60s" && \
postconf -P "submission/inet/cleanup_service_name=subcleanup" && \
/usr/bin/configure-groupoffice-mailserver.php

invoke-rc.d postfix restart
invoke-rc.d dovecot restart
