#!/bin/sh
set -e

case "$1" in
    install|upgrade|configure)

      dpkg-divert --quiet --add --rename --package groupoffice-mailserver --divert /etc/opendkim.conf.original /etc/opendkim.conf

 *)
        echo "preinst called with unknown argument $1" >&2
        exit 1
esac